### ISSUE TITLE
Repair Spot Locations

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#10]
1. 421.498748779297,6482.07666015625,28.8088970184326
Great Ocean Hwy - Farm  [NE]

2. -112.240531921387,6219.4287109375,31.3214416503906
Great Ocean Hwy - Clucking Bell Co. - Power Box on Building  [NE]

3. -286.159545898438,6019.8544921875,31.4759712219238  [WNW]
-289.509246826172,6023.9609375,31.4743328094482   [WNW]
-289.478424072266,6020.0205078125,31.5472011566162  [SSW]
-292.919250488281,6023.42822265625,31.5401000976563  [SSW]
**BIG MISSION:** Great Ocean Hwy - Power Plant (x4)

4. -552.638427734375,5348.05810546875,74.743049621582
Great Ocean Hwy - Lumber Yard Doorside Power Box  [ENE]

5. -505.58544921875,5277.14892578125,80.6101226806641
Great Ocean Hwy - Lumber Yard Generator  [WNW]

6. -1488.42700195313,4983.32470703125,63.5429763793945
Great Ocean Hwy - Park Ranger Office AC Unit  [S]

7. -2192.92358398438,4292.5947265625,49.1740455627441
Great Ocean Hwy - Hookies Seafood Diner Soda Machine  [ESE]

8. -2541.03051757813,2302.447265625,33.2145462036133
Route 68 - Fast Serve Gasoline Power Box   [NWN]

9. -3411.94091796875,970.132934570313,8.34668445587158
Barbareno Rd - Pier Emergency Telephone Box  [W]

10. -3223.15063476563,915.14013671875,13.9924535751343
Barbareno Rd - House Power Box   [ESE]

11. -2956.09008789063,386.831329345703,15.0206880569458
Great Ocean Hwy - Rob's Liquor Power Box  [W]

12. -2980.65161132813,65.3421096801758,11.6085033416748
Great Ocean Hwy - Pacific Bluffs CC Power Box [NNE]

13. -2032.37255859375,-463.892852783203,11.4213390350342
Del Perro Frwy - Parking Lot Toll Booth [WNW]

14. -1586.34924316406,-924.821472167969,9.54731273651123
Red Desert Ave - Pier [WNW]

15. -1668.73107910156,-1051.09899902344,13.1549654006958  [WNW]
-1668.84631347656,-1053.82824707031,13.153977394104  [SSW]
-1646.61376953125,-1078.53979492188,13.1561489105225 [NNE]
**BIG MISSION:** Red Desert Ave - Del Perro Pier Arcade Cabinets 
-1638.72680664063,-1032.53564453125,13.1519565582275  [NNE]
**CONT..** Bathroom Hand Dryer

16. -1807.05358886719,-1223.33776855469,13.0172786712646
Red Desert Ave - End of Pier - Power Generator Box [WNW]

17. -1167.06604003906,-455.106903076172,34.4306755065918
Marathon Ave - Paramount Studios Wall Power Box [NW]

18. -1091.36511230469,-507.236083984375,36.2919616699219
Heritage Way - Paramount Studios Wall Power Box  [SE]

19. -117.317649841309,-61.9465560913086,56.3656692504883
Hawick Ave. - Kushy Farmacy Weed Shop Rear Power Box

20. 450.952423095703,-2.48466920852661,83.1393280029297
Meteor St - 100% Free Parking Side Power Box [WNW]

21. -26.5861339569092,-227.997467041016,46.2933769226074
Occupation Ave. & Capital Blvd - For Rent Rear Power Box  [W]

22. -355.081756591797,-108.534660339355,38.6970291137695
Carcer Way - Los Santos Customs Rear Power Box  [N]

23. -33.9406127929688,-722.843505859375,32.9676094055176
San Andreas Ave - Underpass Power Box  [N]

24. 372.009704589844,-825.378601074219,29.2926654815674
San Andreas Ave & Sinner St. - Los Santos Occier Supply Side Power Box  [ENE]

25. 1172.5859375,-448.052154541016,66.631233215332
Mirror Park Blvd - Reflex Nails Side Power Box  [W]

26. 1662.77795410156,-25.0739593505859,173.774703979492  [NNW]
1672.91076660156,-27.8955326080322,173.774719238281   [NNE]
1659.14343261719,-0.0271100979298353,166.118026733398   [SW]
1665.18884277344,-25.2713871002197,182.769744873047   [SSE]
1665.30041503906,-28.6177253723145,196.936172485352   [SSE]
1664.47314453125,-55.0881843566895,174.170181274414   [E]
**BIG MISSION:** Mirror Park Blvd - Dam

27. 711.148376464844,128.440063476563,80.7544784545898  [S]
708.983215332031,117.616172790527,80.956413269043   [S]
673.544982910156,109.887084960938,80.9142761230469  [SE]
663.594177246094,122.669868469238,80.9229507446289  [N]
670.291137695313,151.370971679688,80.9291534423828   [S]
701.037353515625,162.760757446289,80.9502182006836  [NNE]
**BIG MISSION:** Water and Power Plant

28. 382.881042480469,241.227813720703,103.034660339355 
Power St - Abandoned Building Power Box [W]

29. -20.7758884429932,-1389.19909667969,29.3725662231445
Innocence Blvd - Hands On Car Wash Parking Lot Powerr Box  [E]

30. 312.235015869141,-1868.7099609375,26.9135665893555
Carson Ave & Roy Lowenstein Blvd - Street Side Signal Box   [SSW]

31. 2587.64575195313,5062.650390625,44.9193344116211
Union Rd & Senora Fwy - Power Station  [WSW]

32. 2567.46997070313,2574.98803710938,37.0978889465332  [S]
Senora Ave - Dinosaur holding a hotdog

33. -1174.51098632813,-474.169677734375,49.3554534912109
Paramount Pictures - Rooftop AC Unit  [BIG MONEY]

**Comment by HIsShadowONE** [comment]
has all of this been integrated into missions so i can close or do you still need some of these added ?

**Comment by TheTrueMac** [comment]
Done.
