### ISSUE TITLE
Market Locations/Items

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#11]
Market #1 (Strip Club)
-Milk, Water, Coffee, Tea, Iced Tea, Orange Juice, Goca Cola, Redgull, Lemon Limonad, Vodka, Bread, Donut, Tacos, Sandwich, Kebab, Premium Donut

Market #2 
-Milk, Water, Coffee, Tea, Iced Tea, Orange Juice, Goca Cola, Redgull, Lemon Limonad, Vodka, Bread, Donut, Tacos, Sandwich, Kebab, Premium Donut

Market #3  
-Milk, Water, Coffee, Tea, Iced Tea, Orange Juice, Goca Cola, Redgull, Lemon Limonad, Vodka, Bread, Donut, Tacos, Sandwich, Kebab, Premium Donut

Market #4  
-Milk, Water, Coffee, Tea, Iced Tea, Orange Juice, Goca Cola, Redgull, Lemon Limonad, Vodka, Bread, Donut, Tacos, Sandwich, Kebab, Premium Donut

Market #5 
-Milk, Water, Coffee, Tea, Iced Tea, Orange Juice, Goca Cola, Redgull, Lemon Limonad, Vodka, Bread, Donut, Tacos, Sandwich, Kebab, Premium Donut

**Comment by HIsShadowONE** [comment]
just need to know what kind of store each one is so i can remove irrelevant items , like liquor store , strip club , food mart , and which ones could be substituted for medical drug store , repair kit store etc if any were say not in a gas station or which are gas stations stores , etc ... to have proper RP of which items can be purchased there , most food marts will all have same items , liquor stores only booze and some small food/drink items , and some will need to be selected for alternate item purchases that are required for jobs (as the test two stores indicated by drug icons on map show) so i can change some of these stores to that and change liquor stores from having all these same items.
