### ISSUE TITLE
Drug Spots

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#12]
Cocain  -  
- Cocain Processing  -  

PCP  -  
- PCP Processing  -  2434.65771484375,4964.2080078125,42.3476066589355   [SE]

Ecstasy  -  
- Ecstacy Processing  -  2432.76928710938,4972.09423828125,42.3476066589355  [NW]

Meth - 
- Meth Processing  -  1391.76147460938,3605.97412109375,38.9419364929199

Agave - 510.337371826172,5507.88916015625,773.090270996094
- Tequila Destilling  -  510.337371826172,5507.88916015625,773.090270996094

Shrooms - 959.620666503906,-2207.63940429688,30.5997638702393
- Dry Mushrooms  -

**Comment by HIsShadowONE** [comment]
done and added to the drug system, thanks :)
