### ISSUE TITLE
FiB Computers

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#13]
107.689758300781,-752.304992675781,242.152099609375

125.594688415527,-767.294677734375,242.152008056641

109.823616027832,-747.34765625,242.152282714844

118.953521728516,-731.1318359375,242.151916503906

**Comment by HIsShadowONE** [comment]
added had no way to know which floor or area these were so documentation in code is marked as FiB 1 ,2 ,3 , 4 - need floor names later in case these require changing to know which exact location they are in. but i will close this for now as they are added
