### ISSUE TITLE
Emotes

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#14]
Hansup - (Hands Up) - OK
No - OK
Damn - OK
Dance - OK
Salute - OK
Rock - OK
Sit Chair - OK
Cop - OK
Binoculars - OK 
Cheer - OK
Drink - OK
Smoke - OK
Film - OK
Plant - OK
Guard - OK
Hammer - OK
Hangout - OK
Hiker - OK
Statue - OK
Jog - OK
Lean - OK
Flex - OK
Camera - (Photo) - OK
Sit - OK
Hoe - OK
Hoe 2 - OK
Pushups - (Push Ups) - OK
Impatient - OK
Mobile - OK
Diggit - OK
Sunbath - (Sunbathe Front) - OK
Sunbath 2 - (Sunbathe Back) - OK
Weld - OK
Kneel - OK
Crowdcontrol - (Crowd Control) - OK
Investigate - OK
Yoga - OK
Medic - OK
Notepad - OK
Traffic - **NO**
Clipboard - OK
Coffee - **NO**
Smoke 2 - **NO**
Bum Freeway - (Bum Sign) - **NO**
Bum slumped - (Bum Laying) - OK
Bum Standing - OK
Bum Wash Window - (Wash) - OK
Cop Drill Sargent - (Drill Sergeant) - **NO**
Drug Dealer - **NO**
Drug Dealer 2 - OK
Guard Patrol - OK
Guard Stand 2 - **NO**
Tourist Map - **NO*
Tourist Cell - (Cell Phone Picture) - OK
Window Shop - OK
Smoke Weed - **NO*

**Comment by HIsShadowONE** [comment]
changed miss named emotes - this needs more testing though as some of these emotes you have marked as non functional work for me. will cross check and change ones i cant get to work either.
