### ISSUE TITLE
1 story Villa/Ranch IN/OUT Spawns

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#15]
Front Door: 1396.29138183594,1141.83837890625,114.333648681641  [INSIDE]  [E]
1395.54553222656,1141.80700683594,114.643508911133 [OUTSIDE] [W]

Back Door: 1408.80249023438,1147.33569335938,114.333648681641  [INSIDE]  [W]
1409.75,1147.38305664063,114.33374786377 [OUTSIDE] [E]

Side Door: 1399.39514160156,1128.76062011719,114.333648681641 [INSIDE]  [N]
1399.41125488281,1127.86767578125,114.334442138672  [OUTSIDE]  [S]

Front Side: 1391.12829589844,1132.18298339844,114.333648681641 [INSIDE] [E]
1390.24206542969,1132.18920898438,114.334350585938  [OUTSIDE]  [W]

**Comment by HIsShadowONE** [comment]
im not sure what this set is for - or is this old data not to be used for us marshals

**Comment by TheTrueMac** [comment]
I changed the name of this but it didn't stick I guess. This is for the Villa.

**Comment by HIsShadowONE** [comment]
added
