### ISSUE TITLE
US Marshal Building

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#16]
US Marshal Lobby Elevator to Office: -66.9845657348633,-802.548767089844,44.4180679321289 [S]
US Marshal Lobby Elevator to Roof:  -70.8961868286133,-801.041015625,44.2273292541504 [S]

US Marshal Office Elevator to Lobby: -78.9416275024414,-829.409973144531,243.385848999023

Landing Pad Spawn: -75.0763626098633,-818.919067382813,326.175170898438  [E]

Landing Pad Enter/Exit: -74.9811172485352,-824.098388671875,321.306549072266  [S]  [OUTSIDE]
-72.2383575439453,-824.520080566406,243.385848999023  [W]  [INSIDE]

Garage: -50.0286445617676,-782.504821777344,44.260871887207  [ESE]
Garage [Lower]: -105.918914794922,-868.118286132813,27.5090770721436

Computer 1 - Front Desk: -72.3671035766602,-814.31982421875,243.385833740234  [S]
Computer 2 - Main Office: -80.4466552734375,-801.742370605469,243.405807495117
Computer 3 - Side Room Laptop: -64.9551620483398,-814.785400390625,243.385971069336

Armory: -82.0871887207031,-809.427734375,243.386016845703

Clothing: -78.2997665405273,-812.530700683594,243.385971069336

Balcony: -78.6393737792969,-835.452880859375,269.011352539063  [S]

**Comment by HIsShadowONE** [comment]
added 90% of this - test on dev
did not add balcony tele , clothing  (need clothing hashes) like was done with ems , did not add tele from ground to heli pad (can be abused by players to get to rooftop) will add when permissions can be added to tele's
only added one garage

**Comment by TheTrueMac** [comment]
US Marshal Bldg Edits

Correct Locker Room Cords
-78.3202514648438,-812.522277832031,243.385986328125

Garage to Lobby is out via the elevator, but the elevator returns you outside. Possible solution is to use 
-78.0272827148438,-822.318725585938,243.385971069336
for the Lobby's in/out portal, exiting the and leading back to the garage.

**Comment by HIsShadowONE** [comment]
added *NOTE CLOAKROOM NEEDS PED MODEL NUMBERS TO OPERATE MAY NOT BE REQUIRED DUE TO PERSONAL CLOSET SPACE FOR CHANGING THESE CUSTOM OUTFITS MARSHALS USE AS UNIFORMS*
