### ISSUE TITLE
Crime/Fines

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#18]
-- fines
-- map of name -> money
cfg.fines = {
  ["Speeding"] = 100,
  ["Minor Theft"] = 350,
  ["Manslaughter"] = 3000,
  ["Manslaughter x2"] = 7000,
  ["Manslaughter x3+"] = 10000,
  ["Assault"] = 700,
  ["Assault with intent to rob"] = 2000,
  ["Robbery"] = 500,
  ["Armed Robbery"] = 2000,
  ["Incitement"] = 2000,
  ["Organized Crime"] = 25000,
  ["Blackmail"] = 500,
  ["Bribary"] = 1000,
  ["Arsen"] = 750,
  ["Kidnapping"] = 10000,
  ["Burglary"] = 4000,
  ["Money Laundering"] = 10000,
  ["Grand Theft"] = 5000,
  ["Fleeing and Eluding"] = 2500,
  ["Harrassment"] = 5000,
  ["Safecracking"] = 4500,
  ["Jaywalking"] = 1,
  ["Running a red light"] = 200,
  ["Illegal Parking"] = 10,
  ["Offroading"] = 200,
  ["Trafficking"] = 2000,
  ["Disobeying an Officers command"] = 200,
  ["Animal Cruelty"] = 50,
  ["Intent to sell"] = 500,
  ["Distribution of narcotics"] = 3000,
}

**Comment by HIsShadowONE** [comment]
added
