### ISSUE TITLE
Vehicle Shop Spawns

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#19]
Luxury Car Shop - Thunder Dr.
Buy Menu: -803.930969238281,-224.588439941406,37.223876953125
Preview/Spawn: -808.714294433594,-228.662139892578,38.6152992248535

Car Shop - Power St & Adam's Apple~Blvd
Buy Menu: -29.9161739349365,-1104.61413574219,26.4223518371582
Preview Area/Spawn: -45.3155136108398,-1098.24230957031,26.4223518371582

**Comment by HIsShadowONE** [comment]
added
