### ISSUE TITLE
Bug Report 1

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#3]
NAME: Mac
RP NAME: (if different)
BUG REPORT: Bexxy was stuck in the jerry can animation after pilling up her gas. She had to go to menu>emotes>clear to be able to move freely again.
EFFECT OF BUG: (what result did it cause?)
TIME OF OCCURANCE: 9:30 - 6/14/17
----------------------------------------
         -admin only section-
READ BY: 
STATUS:
NOTES:

**Comment by HIsShadowONE** [comment]
sadly the fuel script is run by a pre written hard coded .dll unlike every other script i use , so not much can be done about changing how things work with it , we will have to just cancel animation to stop jerry can filling.  the only thing i can control is removing the free jerry can picks up entirely
