### ISSUE TITLE
Tesla Crash

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#5]
Pulled out Tesla and game froze and then crashed. "Error pip-sixteen-pizza"

Error pip-sixteen-pizza

"pip-sixteen-pizza"

A pip-sixteen-pizza caused FiveM to stop working. A crash report is being uploaded to the FiveM developers. If you require immediate support, please visit FiveM.net and mention the details below.

Report ID: db08ac29-b6ea-4d86-9376-374a4837879a (use Ctrl+C to copy)

**Comment by TheTrueMac** [comment]
Confirmed crash. Duplicated.

**Comment by HIsShadowONE** [comment]
tesla removed , was redundant with in game version anyways

**Comment by TheTrueMac** [comment]
same issue with f50 now
