### ISSUE TITLE
Repairs

### ISSUE THREAD

**Issue by TheTrueMac** [HIsShadowONE/GTA-RP-SERVER#9]
Repairs seem to be client-side. Repairs made within the vicinity of another player, the only person who can see the repairs is the person repairing.

**Comment by TheTrueMac** [comment]
Results seem to vary. If I repair from fully destroyed (which is possible) and is damaged again, when another citizen see's the vehicle, the level of repair varies.

**Comment by HIsShadowONE** [comment]
solved , but cant be resolved as repairs are client sided and is determined by players proximity to repairs , have players "stand back" from your welding to prevent them from not seeing repairs.
